apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-demo-config
  namespace: app-dev
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/library?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"