apiVersion: v1
kind: ConfigMap
metadata:
  name: library-config
  namespace: library-dev
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/library?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  USER_SERVICE_URL : "http://user-management-service:8080/user-management"
  ALLOWED_ORIGINS : "http://192.168.49.2:30080,http://192.168.49.2:30003"
  USER_SERVICE_SWAGGER_LOCAL_SERVER_URL : "http://192.168.49.2:30003"