apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs-ingress
  namespace: rustfs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: home.lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rustfs-service
                port:
                  number: 9001
  tls:
    - hosts:
        - home.lab.local
      secretName: local-cert-tls
