apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: library-dev
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: library-dev
spec:
  provider:
    vault:
      server: http://vault-service.vault.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: libraryapp
          serviceAccountRef:
            name: vault-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: library-secret
  namespace: library-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: library-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: mysql-db
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: mysql-db
        property: password